### ISSUE TITLE
Small issue in the mobile version

### ISSUE THREAD

**Issue by aldomann** [ploctaux/philippeloctaux.com#1]
As you can see in the image below, there seems to be a small bug in the renderisation of the hamburger icon when browsing the website on a mobile device.
![image](https://cloud.githubusercontent.com/assets/729732/15484937/d8a0ba86-213c-11e6-992e-fcf02b660d11.png)

The issue seems to be in line 84: `</ul>.`; that stop should definitely not be there. I reckon the typo is in all the subpages.

**Comment by ploctaux** [comment]
THANK YOU
I was looking for that bug for SO LONG and I couldn't find it!

but there's no need to change the files (unless you want) cause I'm working on the new website :)

but thanks for the report!

**Comment by aldomann** [comment]
Chrome inspector is your friend :P

**Comment by ploctaux** [comment]
@aldomann I need to relearn chrome dev tools cause it changes so often haha

**Comment by ploctaux** [comment]
if you wanna send a PR with fixes, do it, or I'll just close that issue (I won't fix it by myself)

**Comment by aldomann** [comment]
Too lazy, also if it's the old website, there's no point. But hey, I found a bug that was bugging you, so you have that going for you :P

**Comment by ploctaux** [comment]
thanks haha
